### ISSUE TITLE
Handle Error Messages over 256 Characters

### ISSUE THREAD

**Issue by wjwatkinson** [Shopify/maintenance_tasks#523] opened 2021-11-08 17:33 UTC
The `maintenance_tasks_runs` table `error_message` column is currently a `String`, so it has a character limit of 256. If an error message is over 256 characters it will error out and not be able to log the run.
![image](https://user-images.githubusercontent.com/54151695/140790071-541ad0f9-8a47-44e7-a07e-ad32fdc034bc.png)

The error message should get truncated to the character limit of the column to avoid this error. If 256 seems too small we could also update the column to a `text` column where the character limit would be 30000.

**Comment by nvasilevski** [comment] 2021-11-08 17:35
Hey @wjwatkinson, this seems to be a duplicate of https://github.com/Shopify/maintenance_tasks/issues/493

**Closed as completed** 2021-11-08 18:15 UTC
